cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'caskroom/versions'

brew 'ack'
brew 'coreutils'
brew 'ccze'
brew 'git'
brew 'gifsicle'
brew 'grc'
brew 'imagemagick'
brew 'libgit2'
brew 'openssl'
brew 'maven'
brew 'node'
brew 'readline'
brew 'ruby-build'
brew 'rbenv'
brew 'spark'
brew 'unrar'
brew 'fasd'
brew 'watch'
brew 'wget'
brew 'p7zip'
brew 'zsh-syntax-highlighting'

cask 'adium'
cask 'alfred'
cask 'atom'
cask 'bettertouchtool'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
# A really nice calendar menu app
cask 'itsycal'
#cask 'intellij-idea'
#cask 'seashore'
#cask 'slack'
cask 'vlc'
cask 'jumpcut'
cask 'java'
cask 'java7'
cask 'virtualbox'
#cask 'vagrant'
cask 'sublime-text'
cask 'iterm2'
cask 'menumeters'
